version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_RECAPTCHA_SITE_KEY=${VITE_RECAPTCHA_SITE_KEY}
        - VITE_WEBHOOK_URL=${VITE_WEBHOOK_URL}
        - VITE_WEBHOOK_USERNAME=${VITE_WEBHOOK_USERNAME}
        - VITE_WEBHOOK_PASSWORD=${VITE_WEBHOOK_PASSWORD}
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - default
      - npm_default

networks:
  default:
  npm_default:
    external: true